version: '2.2'

services:
  es01:
    container_name: elk-es01
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    environment:
      - node.name=es01
      - discovery.type=single-node
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD 
      - "ES_JAVA_OPTS=-Xms8g -Xmx8g"
      - bootstrap.memory_lock=false
    volumes: 
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - certs:$CERTS_DIR:z
    ports:
      - 9200:9200
    networks:
      - elk

    # healthcheck:
    #   test: curl --cacert $CERTS_DIR/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5

  kib01:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    container_name: elk-kib01
    restart: always
    env_file: .env
    depends_on:
      - es01
    ports:
      - 5601:5601
    networks:
      - elk
    volumes:
      - certs:$CERTS_DIR:z
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,z

  logs01:
    image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}
    container_name: elk-logs01
    restart: always
    env_file: .env
    depends_on:
      - es01
    ports:
      - "5044:5044"
      - "50000:50000"
      - "9600:9600"
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - certs:$CERTS_DIR:z
      # - ./logstash/ca.crt:/usr/share/logstash/config/ca.crt
      # - lsdata:/usr/share/logstash/data

    environment:
      - xpack.monitoring.elasticsearch.ssl.certificate_authority=$CERTS_DIR/ca/ca.crt
      - "LS_JAVA_OPTS=-Xmx1g -Xms1g"
    networks:
      - elk

  # wait_until_ready:
    # image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    # command: /usr/bin/true
    # depends_on: {"es01": {"condition": "service_healthy"}}

networks:
  elk:
    driver: bridge

volumes: {"lsdata", "certs"}

#volumes: {"data01", "data02", "certs"}
#volumes: {"data01", "lsdata", "certs"}